### ISSUE TITLE
Possible bug, and fix

### ISSUE THREAD

**Issue by andyjessop** [xiaohutai/jsonapi#5]
I'm not sure whether this is a bug, or whether it's just because I'm working locally. I'm hosting the site at `localhost/root`, but some of the links come out with the root as just `localhost`.

To fix this, in the initialise function, I've set:

```
$this->basePath = $this->app['paths']['rooturl'] . $this->base;
```

instead of:

```
$this->basePath = $this->app['paths']['canonical'] . $this->base;
```

and the same change in the helper function makeAbsolutePathToThumbnail().

If this is indeed a bug and I have fixed it, would you like me to submit a pull request?

**Comment by xiaohutai** [comment]
To be honest, I'm not entirely sure what the differences between `rooturl` and `canonical` are.The only thing I notice is that `rooturl` has a trailing slash. Since I can't re-produce your issue, could you paste a dump of your app paths:

```
dump($this->app['paths']);
```

I suppose it _should_ be OK to use `rooturl` after removing the trailing slash.

**Comment by Raistlfiren** [comment]
Closing, please create a new issues if this is still a problem.
