### ISSUE TITLE
Unable to find controller "singleContent".

### ISSUE THREAD

**Issue by zomars** [xiaohutai/jsonapi#56]
Suddenly a client's website started showing this error when trying to access a record with the JSON API:
<img width="916" alt="captura de pantalla 2017-06-29 a las 17 29 53" src="https://user-images.githubusercontent.com/3504472/27714839-a32fdaf8-5cf0-11e7-8563-1461029fa02b.png">
<img width="914" alt="captura de pantalla 2017-06-29 a las 17 29 58" src="https://user-images.githubusercontent.com/3504472/27714840-a49db040-5cf0-11e7-8af9-854612938cbd.png">

I tried updating both Bolt and the extension to their current versions and the problem persists.

Any guidance would be greatly appreciated. 🙏

PS. this is one of the offending urls: http://grupoimpulsora.net/json/productos/amoniaco

**Comment by luccamendonca** [comment]
I ran into this same issue today and the solution seems to be really simple.

On `extensions/vendor/bolt/jsonapi/src/Controllers/ContentController.php` I saw that the connect method uses the controllers factory in a way that doesn't seem to be supported:

`$ctr->get(<route>, <method_name>);`

And by only providing the method name as the second parameter makes Symfony to try to instantiate a controller with that name. For example "singleContent".

Now, you can do a little patch yourself until this is fixed by passing an array containing [$this, <method_name>].

For example: `$ctr->get('/{contentType}/{slug}/{relatedContentType}', [$this, 'singleContent'])`

Of course this should only be done for testing purposes and/or on your development environment, just so you can make stuff work.

I've just created a pull request that should fix this issue for Bolt 3.2, so if everything's okay and I didn't mess anything up we may see an update soon.

**Comment by zomars** [comment]
Thanks for the heads up, I will try it myself and report back if it worked.

**Comment by zomars** [comment]
It worked!

**Comment by luccamendonca** [comment]
Awesome, @zomars! Glad I could help somehow :) Now let's wait to see if @xiaohutai approves the pull-request I made.

Cheers!

**Comment by xiaohutai** [comment]
Thanks @zomars and @luccamendonca for reporting and fixing this!
